name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-latest

    steps:
      - name: Build
        run: xcodebuild -project myNextBooks/MyNextBooks/MyNextBooks.xcodeproj    -scheme MyNextBooks    -sdk iphonesimulator    -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.5' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Test
        run: xcodebuild test -project myNextBooks/MyNextBooks/MyNextBooks.xcodeproj    -scheme MyNextBooks    -sdk iphonesimulator    -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.5' | xcpretty && exit ${PIPESTATUS[0]}
