name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run:
          ls -l
          cd myNextBooks/MyNextBooks
          xcodebuild -project MyNextBooks.xcodeproj    -scheme MyNextBooks    -sdk iphonesimulator    -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.5'
      - name: Test
        run: 
          cd myNextBooks/MyNextBooks
          xcodebuild test -project MyNextBooks.xcodeproj    -scheme MyNextBooks    -sdk iphonesimulator    -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.5' | xcpretty && exit ${PIPESTATUS[0]}
