name: UI Tests workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run UI Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: UI Tests
        env:
          platform: ${{ 'iOS Simulator' }}
          scheme: ${{ 'MyNextBooksUITests' }}
        run: |
           cd MyNextBooks
           xcodebuild test -scheme "$scheme" -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=15.2"
